### ISSUE TITLE
XCode10 编译报错 需要将info.plist 从 Copy Bundle Resources中移除

### ISSUE THREAD

**Issue by zxconan** [xiaomipassport/oauth-iOS-sdk#12]
error: Multiple commands produce '/Users/xinzhang/Library/Developer/Xcode/DerivedData/MiOAuthDemo-dvrskotrjceyntflmaqatoyzurmm/Build/Products/Debug-iphonesimulator/MiOAuthDemo.app/Info.plist':
1) Target 'MiOAuthDemo' (project 'MiOAuthDemo') has copy command from '/Users/xinzhang/workspace/oauth-ios-sdk/MiOAuthDemo/MiOAuthDemo/Info.plist' to '/Users/xinzhang/Library/Developer/Xcode/DerivedData/MiOAuthDemo-dvrskotrjceyntflmaqatoyzurmm/Build/Products/Debug-iphonesimulator/MiOAuthDemo.app/Info.plist'
2) Target 'MiOAuthDemo' (project 'MiOAuthDemo') has process command with output '/Users/xinzhang/Library/Developer/Xcode/DerivedData/MiOAuthDemo-dvrskotrjceyntflmaqatoyzurmm/Build/Products/Debug-iphonesimulator/MiOAuthDemo.app/Info.plist'

**Comment by aofeng2009** [comment]
> error: Multiple commands produce '/Users/xinzhang/Library/Developer/Xcode/DerivedData/MiOAuthDemo-dvrskotrjceyntflmaqatoyzurmm/Build/Products/Debug-iphonesimulator/MiOAuthDemo.app/Info.plist':
> 
> 1. Target 'MiOAuthDemo' (project 'MiOAuthDemo') has copy command from '/Users/xinzhang/workspace/oauth-ios-sdk/MiOAuthDemo/MiOAuthDemo/Info.plist' to '/Users/xinzhang/Library/Developer/Xcode/DerivedData/MiOAuthDemo-dvrskotrjceyntflmaqatoyzurmm/Build/Products/Debug-iphonesimulator/MiOAuthDemo.app/Info.plist'
> 2. Target 'MiOAuthDemo' (project 'MiOAuthDemo') has process command with output '/Users/xinzhang/Library/Developer/Xcode/DerivedData/MiOAuthDemo-dvrskotrjceyntflmaqatoyzurmm/Build/Products/Debug-iphonesimulator/MiOAuthDemo.app/Info.plist'

You are right.
