### ISSUE TITLE
SDK中授权网页只能显示繁体中文

### ISSUE THREAD

**Issue by ayang851** [xiaomipassport/oauth-iOS-sdk#13]
SDK中授权网页只能显示繁体中文，需要如何配置才能显示简体中文

**Comment by ayang851** [comment]
收到的验证码登录短信也为英文

**Comment by ayang851** [comment]
个人认为是个bug，sdk多语言判断有些问题，按正常来说多语言环境应该是依据iphone语言判断的，而该SDk中多语言环境是根据地iphone设置的地区判断的。

**Comment by aofeng2009** [comment]
@iOSDeveloperOfChina 谢谢你的反馈，繁体这个问题比较特殊，下个版本我们做下调整。
