### ISSUE TITLE
SDK授权crash问题

### ISSUE THREAD

**Issue by chunyunwang** [xiaomipassport/oauth-iOS-sdk#14]
0 zhihuiguanjia | _ERR_load_OBJ_strings
1 zhihuiguanjia | _ERR_load_crypto_strings + 32
2 zhihuiguanjia | _curl_global_init + 136
3 zhihuiguanjia | -[MAPhoneNumberUtil init] (MAPhoneNumberUtil.m:44)
4 zhihuiguanjia | +[NSObject(MASingleton) sharedObject] (NSObject+MASingleton.m:27)
5 zhihuiguanjia | +[MAPhoneNumberUtil sharedInstance] (MAPhoneNumberUtil.m:38)
6 zhihuiguanjia | -[MiOAuth setupWithPlatform:appId:redirectUrl:] (MiOAuth.m:112)
7 zhihuiguanjia | -[MiNetworkConnector MJFNetwork_setupMiOauth:redirectUrl:] (MiNetworkConnector.m:25)
8 zhihuiguanjia | -[MHPassport initWithAppId:redirectUrl:delegate:] + 316
9 zhihuiguanjia | -[MHAccount initWithAppId:redirectUrl:delegate:] + 236
10 zhihuiguanjia | -[HYXiaoMiDeviceManager init] (HYXiaoMiDeviceManager.m:62)

以上是bugly上反馈出的堆栈信息

**Comment by chunyunwang** [comment]
[https://bugly.qq.com/v2/crash-reporting/crashes/6e8092ee44/3456903?pid=2,](url)

**Comment by chunyunwang** [comment]
![1557929016929](https://user-images.githubusercontent.com/18022176/57782424-cb1fc980-775e-11e9-89c5-eaa59f13fc2a.jpg)

**Comment by aofeng2009** [comment]
@chunyunwang 是否在Other link flag中 添加了-ObjC ？

**Comment by chunyunwang** [comment]
@aofeng2009 我们编译配置中，确实添加了ObjC

**Comment by aofeng2009** [comment]
目前我们测试的时候还没有复现，最好能提供一个稳定复现的场景。
