### ISSUE TITLE
提供给和家亲的小米SDK，请兼容iOS13  present全屏

### ISSUE THREAD

**Issue by chunyunwang** [xiaomipassport/oauth-iOS-sdk#16]
你好，请将小米sdk授权认证present出的界面，设置为全屏

![2501571274538_ pic](https://user-images.githubusercontent.com/18022176/66970530-6fb48780-f0c0-11e9-93eb-2d6dc99b08e7.jpg)

**Comment by aofeng2009** [comment]
@chunyunwang  We have updated the framework with a parameter named 'fullScreenPresent'.
