### ISSUE TITLE
xcode 10.1 编译报错

### ISSUE THREAD

**Issue by CGseng** [xiaomipassport/oauth-iOS-sdk#17]
ld: warning: Could not find auto-linked framework 'MiAccountLog'
ld: warning: Could not find auto-linked framework 'MiAccountCore'
Undefined symbols for architecture x86_64:
  "___isPlatformVersionAtLeast", referenced from:
      -[MOWebViewController viewDidLoad] in MiOAuth(MOWebViewController.o)
      -[UIView(MPToast) cs_centerPointForPosition:withToast:] in MiOAuth(UIView+MPToast.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by CGseng** [comment]
Demo编译也是同样的错误

**Comment by aofeng2009** [comment]
@CGseng Fixed
