### ISSUE TITLE
未支持bitcode

### ISSUE THREAD

**Issue by lilong01** [xiaomipassport/oauth-iOS-sdk#18]
发现最新的sdk不支持bitcode

**Comment by lilong01** [comment]
![image](https://user-images.githubusercontent.com/6857209/89999192-093ccd80-dcc1-11ea-8918-08dd6fcb9eb5.png)

**Comment by lilong01** [comment]
![image](https://user-images.githubusercontent.com/6857209/89999529-823c2500-dcc1-11ea-92b1-e84dc9326bc7.png)

**Comment by aofeng2009** [comment]
已经调整
