### ISSUE TITLE
UIView+MPToast 分类方法冲突

### ISSUE THREAD

**Issue by openingax** [xiaomipassport/oauth-iOS-sdk#19]
今天调试 SDK 时发现，你们用到了 UIView+MPToast 的分类，但其中分类的方法没加上你们的前缀，导致工程调用 makeToast: 方法时跑到了你们 SDK 实现里了。

想提个建议：
 1、使用到的第三方库，能否使用 cocoaPods 方法引入，而不是把源码拖进工程；
 2、如果直接用第三方的分类源码，能否给方法名加一下前缀以示区分。

**Comment by aofeng2009** [comment]
已经调整，是否还有问题？
