### ISSUE TITLE
米家IoT关于设备接口在哪里查看下载

### ISSUE THREAD

**Issue by Ramonfan** [xiaomipassport/oauth-iOS-sdk#20]
MiOAuth 这个sdk里面我看只有关于认证的相关接口，那么小米Iot文档中心描述的设备接口在哪里查看下载呢？

**Comment by aofeng2009** [comment]
> MiOAuth 这个sdk里面我看只有关于认证的相关接口，那么小米Iot文档中心描述的设备接口在哪里查看下载呢？

具体细节请联系Iot的技术支持
