### ISSUE TITLE
使用有警告

### ISSUE THREAD

**Issue by cenlei1988** [xiaomipassport/oauth-iOS-sdk#3]
warning: (arm64) /Users/qidu/dev/xiaomi/iosoauthsdk/build/MiPassportDemo.build/Release-iphoneos/MiPassport.build/Objects-normal/arm64/SBJSON.o unable to open object file: No such file or directory
warning: (arm64) /Users/qidu/dev/xiaomi/iosoauthsdk/build/MiPassportDemo.build/Release-iphoneos/MiPassport.build/Objects-normal/arm64/SBJsonBase.o unable to open object file: No such file or directory
warning: (arm64) /Users/qidu/dev/xiaomi/iosoauthsdk/build/MiPassportDemo.build/Release-iphoneos/MiPassport.build/Objects-normal/arm64/SBJsonParser.o unable to open object file: No such file or directory
warning: (arm64) /Users/qidu/dev/xiaomi/iosoauthsdk/build/MiPassportDemo.build/Release-iphoneos/MiPassport.build/Objects-normal/arm64/SBJsonWriter.o unable to open object file: No such file or directory
warning: (arm64) /Users/qidu/dev/xiaomi/iosoauthsdk/build/MiPassportDemo.build/Release-iphoneos/MiPassport.build/Objects-normal/arm64/MiPassport.o unable to open object file: No such file or directory
warning: (arm64) /Users/qidu/dev/xiaomi/iosoauthsdk/build/MiPassportDemo.build/Release-iphoneos/MiPassport.build/Objects-normal/arm64/MPAuthorizeDialog.o unable to open object file: No such file or directory
warning: (arm64) /Users/qidu/dev/xiaomi/iosoauthsdk/build/MiPassportDemo.build/Release-iphoneos/MiPassport.build/Objects-normal/arm64/MPRequest.o unable to open object file: No such file or directory
warning: (arm64) /Users/qidu/dev/xiaomi/iosoauthsdk/build/MiPassportDemo.build/Release-iphoneos/MiPassport.build/Objects-normal/arm64/GTMBase64.o unable to open object file: No such file or directory

是不是工程设置里面用了绝对路径？  ：/Users/qidu/...

**Comment by ssc31803** [comment]
SDK已更新。
