### ISSUE TITLE
Class MPRequest is implemented in both /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer (0x1b71cd708) and /var/containers/Bundle/Application/5230FA9D-58E5-42FE-812C-39C0C184B0EF/sj.app/sj (0x105be35f0). One of the two will be used. Which one is undefined.

### ISSUE THREAD

**Issue by HeterPu** [xiaomipassport/oauth-iOS-sdk#8]
Class MPRequest is implemented in both /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer (0x1b71cd708) and /var/containers/Bundle/Application/5230FA9D-58E5-42FE-812C-39C0C184B0EF/xx.app/xx (0x105be35f0). One of the two will be used. Which one is undefined.

**Comment by ssc31803** [comment]
Fixed
