### ISSUE TITLE
demo 编译错误

### ISSUE THREAD

**Issue by Copypeng** [xiaomipassport/oauth-iOS-sdk#9]
demo 编译错误：

'/Users/ssc/Develop/MiAccount/MiOAuth/MiOAuthDemo/MiOAuthDemo/PrefixHeader.pch' file not found

应该是 hardcode 了 prefixheader 的路径。

![bug](https://user-images.githubusercontent.com/3678212/37023319-78a18414-2160-11e8-86a3-1f606ec8212b.png)

**Comment by ssc31803** [comment]
Fixed.
Thanks.
